import type { ImgHTMLAttributes } from "react";

/**
 * Renders a `<picture>` that serves a WebP version with the original raster as a
 * fallback. Pass the original `src` (e.g. "/team/jane.jpg"); the matching `.webp`
 * must exist alongside it (generated by `scripts/convert-images-webp.mjs` and
 * committed). Browsers that support WebP fetch the smaller file; everything else
 * falls back to the original. og:image / JSON-LD still reference the original, so
 * those keep working.
 *
 * The `<picture>` wrapper uses `display:contents` so it is layout-transparent - the
 * `<img>` participates in the parent layout exactly as a bare `<img>` would, and all
 * `<img>` props (alt, width, height, className, loading, ...) are forwarded.
 */
type PictureProps = ImgHTMLAttributes<HTMLImageElement> & { src: string };

const LOCAL_RASTER = /\.(jpe?g|png)$/i;

export function Picture({ src, ...imgProps }: PictureProps) {
  // External URLs and non-raster sources (e.g. SVG) have no generated .webp sibling.
  if (!LOCAL_RASTER.test(src) || /^https?:\/\//i.test(src)) {
    // eslint-disable-next-line jsx-a11y/alt-text -- alt is forwarded via imgProps
    return <img src={src} {...imgProps} />;
  }
  const webp = src.replace(LOCAL_RASTER, ".webp");
  return (
    <picture className="contents">
      <source srcSet={webp} type="image/webp" />
      {/* eslint-disable-next-line jsx-a11y/alt-text -- alt is forwarded via imgProps */}
      <img src={src} {...imgProps} />
    </picture>
  );
}
