// scripts/llms-journeys.test.mjs
//
// Pins the COMMITTED AI-facing reference files (public/llms.txt and
// public/llms-full.txt, regenerated by scripts/generate-llms.mjs on every
// build) to the data modules: every page family prints the URL of the page it
// summarizes, so an answer engine reading either file can cite the page rather
// than the site root; the attorney journey family is covered end to end; the
// Key Pages block names every hub and the entity, roster, and conversion
// pages; and the team lines carry no credential outside the degree list.
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { SITE_URL } from "./lib/site.mjs";
import { journeys } from "../src/data/journeys.ts";
import { caseTypes } from "../src/data/caseTypes.ts";
import { credentials } from "../src/data/credentials.ts";
import { guides } from "../src/data/guides.ts";
import { methods } from "../src/data/methods.ts";
import { comparisons } from "../src/data/comparisons.ts";
import { knowledgeGuides } from "../src/data/knowledge.ts";
import { insightPosts } from "../src/data/insights.ts";
import { whitePapers } from "../src/data/whitePapers.ts";
import { pillarServices } from "../src/data/services.ts";
import { faqs } from "../src/data/faqs.ts";
import { team } from "../src/data/team.ts";
import { ATTORNEY_STAGES, stageIndexIntro } from "../src/lib/attorney-stages.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const llms = readFileSync(join(ROOT, "public", "llms.txt"), "utf8");
const full = readFileSync(join(ROOT, "public", "llms-full.txt"), "utf8");

// The hubs and the entity, roster, and conversion pages an answer engine
// needs a direct pointer to (a fixed list on purpose: /privacy, /terms, and
// the like do not belong in Key Pages).
const KEY_PAGES = [
  "/about", "/team", "/services", "/case-types", "/credentials", "/guides", "/methods", "/compare",
  "/knowledge", "/insights", "/white-papers", "/attorneys", "/case-studies", "/resources/faq",
  "/locations", "/jurisdictions", "/contact", "/schedule-consultation", "/llms-full.txt",
];
const keyPagesBlock = llms.slice(llms.indexOf("## Key Pages"), llms.indexOf("## Related Practices"));

describe("public/llms.txt (concise)", () => {
  it("Key Pages names every hub and the entity, roster, and conversion pages", () => {
    for (const path of KEY_PAGES) expect(keyPagesBlock, path).toContain(`${SITE_URL}${path}`);
  });

  it("lists every pillar service, case type, and credential page by URL", () => {
    for (const s of pillarServices()) expect(llms).toContain(`(${SITE_URL}/services/${s.slug})`);
    for (const c of caseTypes) expect(llms).toContain(`${SITE_URL}/case-types/${c.slug}`);
    for (const c of credentials) expect(llms).toContain(`${SITE_URL}/credentials/${c.slug}`);
  });

  it("names each active team member with the profile URL and no credential list", () => {
    for (const m of team.filter((t) => !t.memoriam)) {
      expect(llms).toContain(`- ${m.name} - ${m.title} (${SITE_URL}/team/${m.slug})`);
    }
    expect(llms).not.toMatch(/CLCP|CNLCP|\bCRC\b|MSCC/);
  });

  it("covers the attorney journey hub and every stage index with the intro the page renders", () => {
    expect(llms).toContain(`${SITE_URL}/attorneys`);
    for (const stage of ATTORNEY_STAGES) {
      expect(llms).toContain(`- ${stage.label} (${SITE_URL}/attorneys/${stage.slug}): ${stageIndexIntro(stage.slug)}`);
    }
  });

  it("describes the credentials pages as references, and the sister practices by role only", () => {
    expect(llms).toContain("make no claim that the practice or any named person holds an association membership");
    // The generator's own prose (the Related Practices note and the credentials
    // note) names no sister-practice service or brand. The one "life care
    // planner" mention in the file is the life-care-plan costing service's own
    // description (services.ts carve-out), which is the page copy, not the note.
    const related = llms.slice(llms.indexOf("## Related Practices"));
    expect(related).not.toMatch(/vocational evaluation|vocational expert|life care planner|Life Care Planning|KWVRS|kwlcp/i);
    expect(related).toContain("Employability and post-injury work-capacity opinions and life care plan authorship are performed by sister practices");
    expect(llms).not.toMatch(/vocational expert|Life Care Planning|CLCP|CNLCP/);
  });

  it("keeps the house style: hyphens only", () => {
    expect(llms).not.toMatch(/[–—§]/);
  });
});

describe("public/llms-full.txt (comprehensive)", () => {
  it("prints a URL for every editorial page", () => {
    for (const g of guides) expect(full).toContain(`URL: ${SITE_URL}/guides/${g.slug}`);
    for (const m of methods) expect(full).toContain(`URL: ${SITE_URL}/methods/${m.slug}`);
    for (const c of comparisons) expect(full).toContain(`URL: ${SITE_URL}/compare/${c.slug}`);
    for (const k of knowledgeGuides) expect(full).toContain(`URL: ${SITE_URL}/knowledge/${k.slug}`);
    for (const p of insightPosts) expect(full).toContain(`URL: ${SITE_URL}/insights/${p.slug}`);
    for (const w of whitePapers) expect(full).toContain(`URL: ${SITE_URL}/white-papers/${w.slug}`);
  });

  it("prints a URL for every case type, credential, and pillar service, plus the fee and process pages", () => {
    for (const c of caseTypes) expect(full).toContain(`URL: ${SITE_URL}/case-types/${c.slug}`);
    for (const c of credentials) expect(full).toContain(`URL: ${SITE_URL}/credentials/${c.slug}`);
    for (const s of pillarServices()) {
      expect(full).toContain(`Page: ${SITE_URL}/services/${s.slug}`);
      expect(full).toContain(
        `Fees and process: ${SITE_URL}/services/${s.slug}/cost, ${SITE_URL}/services/${s.slug}/process, ${SITE_URL}/services/${s.slug}/timeline`,
      );
    }
    expect(full).toContain("Cost drivers:");
  });

  it("covers every attorney journey page with its URL, intro, and FAQ pairs", () => {
    expect(full).toContain("## Attorney Journey Guides");
    for (const stage of ATTORNEY_STAGES) expect(full).toContain(`(${SITE_URL}/attorneys/${stage.slug})`);
    for (const j of journeys) {
      expect(full).toContain(`URL: ${SITE_URL}/attorneys/${j.stage}/${j.caseTypeSlug}`);
      for (const f of j.faqs) expect(full).toContain(`Q: ${f.question}`);
    }
  });

  it("prints the service FAQ each pillar page renders and the site FAQ with its URL", () => {
    for (const s of pillarServices()) {
      for (const f of s.faqs ?? []) expect(full).toContain(`Q: ${f.question}`);
    }
    expect(full).toContain(`URL: ${SITE_URL}/resources/faq`);
    for (const f of faqs) expect(full).toContain(f.question.replace(/\[\[\/[^|\]]*\|([^\]]+)\]\]/g, "$1"));
  });

  it("exports the white papers' open content only (abstract, takeaways, section headings)", () => {
    for (const w of whitePapers) {
      expect(full).toContain(`Abstract: ${w.summary}`);
      expect(full).toContain(`Sections: ${w.sections.map((s) => s.heading).join("; ")}`);
      // Gated section bodies never leave the page's email gate.
      for (const s of w.sections.slice(1)) {
        const firstSentence = s.bodyHtml.replace(/<[^>]+>/g, "").trim().slice(0, 60);
        if (firstSentence.length > 20) expect(full).not.toContain(firstSentence);
      }
    }
  });

  it("prints degree credentials only for the team and carries no marker syntax", () => {
    expect(full).not.toMatch(/CLCP|CNLCP|\bCRC\b|MSCC/);
    expect(full).not.toMatch(/Credentials: /);
    expect(full).not.toContain("[[/");
    expect(full).not.toMatch(/[–—§]/);
  });
});
